"""empty message

Revision ID: cc1109c65ecc
Revises: b5f7efeff3ee
Create Date: 2017-03-04 14:05:54.377423

"""

# revision identifiers, used by Alembic.
revision = 'cc1109c65ecc'
down_revision = 'b5f7efeff3ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(), nullable=True))
    op.drop_column('users', 'favorite_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
